//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesajlasmaPlatformu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int gmId { get; set; }
        public int gmgrupId { get; set; }
        public Nullable<int> gmuserId { get; set; }
    
        public virtual Grup Grup { get; set; }
        public virtual User User { get; set; }
    }
}
